# -*- coding: utf-8 -*-
# Generado desde extraccion_cartera.py del usuario. NO editar a mano.

SERVIDORES_LATAM = [{'db': 'casita_newSystem_gtm', 'host': 'guatemala-casita.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA CASITA', 'pais': 'Guatemala'},
 {'db': 'presico_newSystem_gtm', 'host': 'guatemala-presico.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESICO', 'pais': 'Guatemala'},
 {'db': 'pistiyo_gtm', 'host': 'guatemala-pistiyo.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PISTIYO', 'pais': 'Guatemala'},
 {'db': 'peru_casita', 'host': 'peru-casita.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA CASITA', 'pais': 'Peru'},
 {'db': 'peru_presico', 'host': 'peru-presico.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESICO', 'pais': 'Peru'},
 {'db': 'salvador_pistiyo', 'host': 'salvador-pistiyo.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PISTIYO', 'pais': 'El Salvador'},
 {'db': 'salvador_moderna', 'host': 'salvador-moderna.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA MODERNA', 'pais': 'El Salvador'},
 {'db': 'colombia_presico', 'host': 'colombia-presico.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESICO', 'pais': 'Colombia'},
 {'db': 'honduras_pistiyo', 'host': 'honduras-pistiyo.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PISTIYO', 'pais': 'Honduras'},
 {'db': 'nicaragua_pistiyo', 'host': 'nicaragua-pistiyo.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PISTIYO', 'pais': 'Nicaragua'}]

SERVIDORES_MEXICO = [{'db': 'lamoderna_newSystem_2', 'host': 'lamoderna-new-system.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA MODERNA'},
 {'db': 'ciudadespresico_newSystem_mx', 'host': 'ciudadespresico-new-system-mx.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESICO CD'},
 {'db': 'guerita_newSystem_mx', 'host': 'guerita-new-system-mx.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA GUERITA'},
 {'db': 'lalupita_newSystem_mx', 'host': 'lalupita-new-system-mx.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA LUPITA'},
 {'db': 'casita_newSystem_mx', 'host': 'casita-new-system-mx.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'LA CASITA'},
 {'db': 'presico_devSystem_mx', 'host': 'presico-dev-system-mx.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESICO MX'},
 {'db': 'prestamosunidos', 'host': 'mexico-prestamosunidos.cfogdzqqzoae.us-east-1.rds.amazonaws.com', 'marca': 'PRESTAMOS UNIDOS'}]

ORDEN_COLUMNAS_LATAM = ['Corte',
 'MARCA',
 'PAIS',
 'coordinadora_id',
 'ruta_id',
 'ruta',
 'zona_id',
 'cliente_id',
 'cliente_final_id',
 'id_desembolso',
 'dia_visita',
 'fecha_desembolso',
 'tipo_desembolso',
 'MONTO_DESEMBOLSO',
 'total_pago_interes',
 'total_pago_proteccion',
 'Total_a_pagar',
 'pago_semanal',
 'plazo',
 'pagosRealizados',
 'pago_capital',
 'pago_interes',
 'colocado_ci',
 'colocado_si',
 'MORA_CI',
 'MORA_SI',
 'colocado_pp',
 'colocado_pp_mora',
 'dias_de_atraso',
 'cobranza_exigible_del_dia',
 'cobro_real_del_dia',
 'fecha_finalizacion',
 'vencido_con_interes',
 'vencido_sin_interes',
 'fecha_ultimo_pago',
 'Monto_ultimo_pago',
 'dbc_cliente_id',
 'Nombre_Cliente',
 'Localidad',
 'id_y_localidad',
 'CAMBIO_COORDINAODRA',
 'coordinadora_prinsipal',
 'coordinadora_secundaria',
 'vueltas',
 'fecha_cambio_coordinadora',
 'colocado_con_interes_fp',
 'vencido_con_interes_fp']

ORDEN_COLUMNAS_MEXICO = ['Corte',
 'Marca',
 'coordinadora_id',
 'ruta_id',
 'ruta',
 'zona_id',
 'cliente_id',
 'cliente_final_id',
 'id_desembolso',
 'dia_visita',
 'fecha_desembolso',
 'tipo_desembolso',
 'MONTO_DESEMBOLSO',
 'total_pago_interes',
 'total_pago_proteccion',
 'Total_a_pagar',
 'pago_semanal',
 'plazo',
 'pagosRealizados',
 'pago_capital',
 'pago_interes',
 'colocado_ci',
 'colocado_si',
 'MORA_CI',
 'MORA_SI',
 'colocado_pp',
 'colocado_pp_mora',
 'dias_de_atraso',
 'cobranza_exigible_del_dia',
 'cobro_real_del_dia',
 'fecha_finalizacion',
 'vencido_con_interes',
 'vencido_sin_interes',
 'fecha_ultimo_pago',
 'Monto_ultimo_pago',
 'dbc_cliente_id',
 'Nombre_Cliente',
 'Localidad',
 'id_y_localidad',
 'CAMBIO_COORDINAODRA',
 'coordinadora_prinsipal',
 'coordinadora_secundaria',
 'vueltas',
 'fecha_cambio_coordinadora',
 'colocado_con_interes_fp',
 'vencido_con_interes_fp']

URL_RUTAS_VALIDACION = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQhqmaTh2F_z9GmZOGAHmaDxgqCYVEH7GwZcuPJs9JITP5QsOa2VeMfygQ4dNq-DQ/pub?output=csv'
